export const data = {
  products: [
    {
      name: 'Satin Silk Saree with Sequins Border',
      slug: 'datin-silk-saree',
      category: 'Saree',
      image: '/images/6.webp',
      price: 3770,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular saree',
    },
    {
      name: 'Organza Sequinned Saree',
      slug: 'organza-sequinned-saree',
      category: 'Saree',
      image: '/images/3.webp',
      price: 5070,
      rating: 4.8,
      numReviews: 3,
      countInStock: 10,
      description: 'A popular saree',
    },
    {
      name: 'Light Green Georgette Saree with Floral Motifs',
      slug: 'light-green-gecasterte-saree',
      category: 'Saree',
      image: '/images/4.webp',
      price: 4160,
      rating: 4.4,
      numReviews: 15,
      countInStock: 30,
      description: 'A popular saree',
    },
    {
      name: 'Black and White Organza Digital Printed Saree',
      slug: 'black-and-white-organza-digital-printed-saree',
      category: 'Saree',
      image: '/images/1.webp',
      price: 4030,
      rating: 4.1,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular saree',
    },
    {
      name: 'Pink Satin Silk Foil Printed Saree',
      slug: 'pink-satin-foil-printed-saree',
      category: 'Saree',
      image: '/images/5.webp',
      price: 4225,
      rating: 4.7,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular saree',
    },
    {
      name: 'Blue Satin Georgette Saree',
      slug: 'blue-satin-georgette-saree',
      category: 'Saree',
      image: '/images/2.webp',
      price: 3835,
      rating: 4.9,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular saree',
    },
  ],
};
